In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob

In [2]:
github_dir = '/home/qzeng_salk_edu/project/241207_zhwu_ml/aging-gene-prediction/ml_output/'

In [3]:
ct = 'L6_CT_CTX_Glut'

In [4]:
path = f'/home/qzeng_salk_edu/project/241207_zhwu_ml/aging-gene-prediction/ml_output/{ct}/result.csv'
ct = path.split('/')[-2]
ml_out = pd.read_csv(path)

In [5]:
# select DEG == pred, and DEG == -1 ,
tmp_ml_out = ml_out[(ml_out['pred'] == ml_out['DEG']) & (ml_out['DEG'] == 1)].copy()
# add std columns as std among dmr	mcg_genebody	mch_genebody	atac	hic_loop	hic_abc_dmr	hic_abc_peak
tmp_ml_out['std'] = tmp_ml_out[['dmr', 'mcg_genebody', 'mch_genebody', 'atac', 'hic_loop', 'hic_abc_dmr', 'hic_abc_peak']].std(axis=1)
# sort by the max std
tmp_ml_out = tmp_ml_out.sort_values('std', ascending=False)
tmp_ml_out.head(15)

,cell_type,gene,DEG,pred,dmr,mcg_genebody,mch_genebody,atac,hic_loop,hic_abc_dmr,hic_abc_peak,std
355,L6_CT_CTX_Glut,Cacna2d3,1,1,0.020578,0.035618,0.127400,0.042365,0.748052,0.017763,0.008224,0.269822
260,L6_CT_CTX_Glut,Ctnna3,1,1,0.128588,0.027605,0.071118,0.056333,0.693684,0.013778,0.008894,0.246353
224,L6_CT_CTX_Glut,Hs6st3,1,1,0.036164,0.047703,0.150136,0.034888,0.687041,0.023541,0.020527,0.244092
306,L6_CT_CTX_Glut,Klf12,1,1,0.040326,0.039314,0.088580,0.042409,0.687899,0.046170,0.055301,0.240955
205,L6_CT_CTX_Glut,B3galt1,1,1,0.059792,0.052069,0.077339,0.097335,0.649939,0.037021,0.026504,0.224862
420,L6_CT_CTX_Glut,Kirrel3,1,1,0.049485,0.046092,0.185244,0.068753,0.595771,0.022343,0.032311,0.207060
2092,L6_CT_CTX_Glut,Cntnap2,1,1,0.077185,0.019907,0.093596,0.146609,0.582968,0.048460,0.031275,0.198716
2107,L6_CT_CTX_Glut,Dgkb,1,1,0.030575,0.023335,0.145798,0.132445,0.540802,0.075799,0.051247,0.181778
194,L6_CT_CTX_Glut,Rasal2,1,1,0.071177,0.067892,0.168806,0.112418,0.508254,0.043371,0.028082,0.167801
2079,L6_CT_CTX_Glut,Zbtb20,1,1,0.107558,0.034273,0.232020,0.111313,0.452384,0.015427,0.047024,0.154494
2199,L6_CT_CTX_Glut,Tenm2,1,1,0.334193,0.010876,0.074559,0.146704,0.376400,0.038107,0.019162,0.152492
368,L6_CT_CTX_Glut,Kctd16,1,1,0.050877,0.097112,0.284993,0.103994,0.382835,0.045316,0.034875,0.136033
1078,L6_CT_CTX_Glut,Grid1,1,1,0.107313,0.035222,0.136075,0.192771,0.423027,0.050386,0.055206,0.135471
2103,L6_CT_CTX_Glut,Tmem135,1,1,0.086042,0.038721,0.232294,0.108468,0.411606,0.076253,0.046616,0.134894
1133,L6_CT_CTX_Glut,Mbd5,1,1,0.086688,0.068539,0.069206,0.121458,0.434179,0.109417,0.110513,0.130124

In [6]:
ml_out[ml_out['gene'] == 'Akt3']

,cell_type,gene,DEG,pred,dmr,mcg_genebody,mch_genebody,atac,hic_loop,hic_abc_dmr,hic_abc_peak
1220,L6_CT_CTX_Glut,Akt3,1,1,0.136492,0.082496,0.077728,0.091289,0.429474,0.065355,0.117167

In [13]:
# #tmp_ml_out select rows with hic_abc_peak as biggest value, then sort by std
# tmp_ml_out = tmp_ml_out.loc[tmp_ml_out['hic_abc_peak'] > 0.5]
# tmp_ml_out = tmp_ml_out.sort_values(by='std', ascending=False)

In [14]:
# peak_abc = f"/home/qzeng_salk_edu/project/241207_zhwu_ml/aging-gene-prediction/ml_input/{ct}/{ct}.abc_enhancer.peak_gene.csv"
# peak_abc = pd.read_csv(peak_abc)
# peak_abc['distance'] = abs(peak_abc['start']  - peak_abc['gene_start'])
# peak_abc

In [15]:
# for gene in tmp_ml_out['gene'].values:
#     _tmp = peak_abc[peak_abc['gene_name'] == gene ]
#     sel_cols = ['2mo.activity', '2mo.contact',  '18mo.activity', '18mo.contact']
#     _tmp = _tmp[sel_cols].mean()
#     if _tmp['2mo.contact'] > _tmp['18mo.contact']:
#         print(gene)