In [1]:
import glob
import pandas as pd
from tqdm import tqdm
import numpy as np
import pandas as pd
import scanpy as sc
import anndata
from scipy.stats import zscore
import seaborn as sns
from tqdm import tqdm
from matplotlib import pyplot as plt
from ALLCools.plot import *
from matplotlib.backends.backend_pdf import PdfPages
from scipy.stats import zscore
from wmb import mm10

plt.rcParams['figure.dpi'] = 100
plt.rcParams['savefig.dpi']=300
plt.rcParams['pdf.fonttype']=42

In [2]:
tf_table= pd.read_csv(f"/home/qzeng/ref/mouse/allTFs_mm.gene_info.csv", index_col = 0)
tf_table.head()

           gene_name             gene_id
gene_alias
Bcl6b          Bcl6b  ENSMUSG00000000317
Zscan26      Zscan26  ENSMUSG00000022228
Mtf1            Mtf1  ENSMUSG00000028890
Klf9            Klf9  ENSMUSG00000033863
Zic5            Zic5  ENSMUSG00000041703

In [3]:
dir_path = '/home/qzeng/project/aging/240518_redo_aDMG/DEGs'

all_df =[]
for fp in tqdm(glob.glob(f'{dir_path}/*')):
    ct = fp.split('/')[-1].split('.')[0]
    tmpdf = pd.read = pd.read_csv(fp, index_col =0)
    tmpdf['log2(aged/young)'] = -tmpdf['avg_log2FC']
    tmpdf['-log(p)'] = -np.log(tmpdf['p_val'] + 1e-50)
    tmpdf['celltype'] = ct
    shared_genes = list(set(tf_table['gene_name']) & set(tmpdf.index)) 
    tmpdf = tmpdf.loc[shared_genes]
    all_df.append(tmpdf)
    
all_df = pd.concat(all_df, axis = 0)
all_df.head()

100%|███████████████████████████████████████████| 80/80 [00:01<00:00, 63.48it/s]

,p_val,avg_log2FC,pct.1,pct.2,p_val_adj,log2(aged/young),-log(p),celltype
Nr2c1,0.631916,0.486282,0.059,0.043,1.0,-0.486282,0.458999,ABC_NN
Zfp13,0.322705,1.272158,0.010,0.003,1.0,-1.272158,1.131015,ABC_NN
Ran,0.628483,-0.727842,0.010,0.020,1.0,0.727842,0.464446,ABC_NN
Zfp830,0.862876,-0.464808,0.007,0.011,1.0,0.464808,0.147484,ABC_NN
Zfp182,0.448942,-0.395999,0.135,0.166,1.0,0.395999,0.800861,ABC_NN

In [4]:
all_df = all_df[all_df['p_val'] < 0.05]

In [5]:
gene_names = [
    "Fra1", 
    "Batf", 
    "Fosl2", 
    "AP-1", 
    "Fos", 
    "JunB", 
    "Jun-AP1", 
    "Atf3", 
    "Fra2",
    'Jun'
]

In [6]:
all_df[all_df.index.isin(gene_names)].sort_values('log2(aged/young)')

,p_val,avg_log2FC,pct.1,pct.2,p_val_adj,log2(aged/young),-log(p),celltype
Fos,1.293625e-07,3.467774,0.012,0.001,3.360061e-03,-3.467774,15.860647,L5_IT_CTX_Glut
Fosl2,1.238026e-02,3.179706,0.061,0.000,1.000000e+00,-3.179706,4.391652,L5_PPP_Glut
Jun,3.897906e-09,2.427818,0.032,0.006,1.012442e-04,-2.427818,19.362826,STR_D1_Sema5a_Gaba
Jun,4.970124e-02,2.056956,0.027,0.000,1.000000e+00,-2.056956,3.001725,PAL-STR_Gaba-Chol
Jun,1.371125e-02,1.647023,0.126,0.037,1.000000e+00,-1.647023,4.289539,NLOT_Rho_Glut
Jun,2.076612e-04,1.495982,0.012,0.004,1.000000e+00,-1.495982,8.479603,RLP_Neur
Fosl2,4.851112e-13,1.223542,0.023,0.010,1.260028e-08,-1.223542,28.354398,DG_Glut
Fosl2,4.371598e-03,1.212514,0.037,0.019,1.000000e+00,-1.212514,5.432627,L23_IT_CTX_Glut
Jun,1.692194e-07,1.113814,0.010,0.005,4.395305e-03,-1.113814,15.592070,STR_D12_Gaba
Jun,1.559691e-02,0.981822,0.043,0.021,1.000000e+00,-0.981822,4.160683,STR-PAL_Chst9_Gaba
Jun,1.574966e-32,0.968931,0.081,0.042,4.090817e-28,-0.968931,73.228489,DG_Glut
Jun,3.182068e-03,0.910962,0.011,0.006,1.000000e+00,-0.910962,5.750224,CA1-ProS_Glut
Jun,2.232442e-02,0.762130,0.021,0.012,1.000000e+00,-0.762130,3.802074,Astro-TE_NN
Jun,1.066122e-11,0.660519,0.022,0.014,2.769146e-07,-0.660519,25.264408,Oligo_NN
Jun,2.098686e-02,0.566107,0.054,0.037,1.000000e+00,-0.566107,3.863859,LA-BLA-BMA-PA_Glut
Fosl2,2.932067e-02,-0.860349,0.015,0.028,1.000000e+00,0.860349,3.529463,LA-BLA-BMA-PA_Glut
Fosl2,4.061870e-02,-1.000000,0.000,0.012,1.000000e+00,1.000000,3.203527,COAp_Grxcr2_Glut
Fosl2,1.584241e-02,-1.049169,0.008,0.025,1.000000e+00,1.049169,4.145064,L23_IT_PIR-ENTl_Glut
Fosl2,3.229417e-02,-2.155278,0.000,0.057,1.000000e+00,2.155278,3.432869,OB-in_Frmd7_Gaba
Fosl2,9.661813e-03,-2.192902,0.007,0.036,1.000000e+00,2.192902,4.639574,CEA-BST_Six3_Cyp26b1_Gaba

In [29]:
tf_table[tf_table.index.isin(gene_names)]

           gene_name             gene_id
gene_alias
Atf3            Atf3  ENSMUSG00000026628
Jun              Jun  ENSMUSG00000052684
Fosl2          Fosl2  ENSMUSG00000029135
Fos              Fos  ENSMUSG00000021250
Batf            Batf  ENSMUSG00000034266